project:
  type: website

website:
  title: "学習ノート"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: topics/index.qmd
        text: Topics
      - href: archive/index.qmd
        text: Archive
      - href: about.qmd
        text: About

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



